### ISSUE TITLE
Practica 6 _Edwin Ortiz Cruz

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-de-irving#2]
[Actividad-6_Cuestionario.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-de-irving/files/9895046/Actividad-6_Cuestionario.pdf)

**Comment by Heidi-19** [comment]
Calificación = 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
