### ISSUE TITLE
ReporteDeActividad#6-EquipoIrving

### ISSUE THREAD

**Issue by Diego047** [SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-de-irving#3]
[Actividad-6_Cuestionario.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-de-irving/files/9956428/Actividad-6_Cuestionario.pdf)

**Comment by Heidi-19** [comment]
Calificación = 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
